#!/bin/sh
if [ "$PKG_UPGRADE" != 1 ]; then
	uci batch <<-EOF
		set luci.themes.Bootstrap_SSRPink=/luci-static/bootstrap-ssrpink
		set luci.main.mediaurlbase=/luci-static/bootstrap-ssrpink
		commit luci
	EOF
fi

exit 0
